### ISSUE TITLE
Change in the Register UI

### ISSUE THREAD

**Issue by pyam-bee** [pyam-bee/OneByte-DineIn#4]
Change the color of the interface of register and staff login

**Comment by Subrina-bhandari** [comment]
The issue with the color of the interface of register and staff login has been updated. Below is the screenshot of the code which I used to make some changes on the color combination. 
<img width="440" alt="loginn" src="https://github.com/pyam-bee/OneByte-DineIn/assets/119728073/9e33e1f5-c798-45ab-bbb2-32c8eba0595f">
<img width="394" alt="Screenshot" src="https://github.com/pyam-bee/OneByte-DineIn/assets/119728073/e75f1a6c-eeb5-439d-8f1c-7fd42a016662">
![image](https://github.com/pyam-bee/OneByte-DineIn/assets/119728073/a5d5bfa7-afe5-4ec5-87b4-d419dd323f27)
