### ISSUE TITLE
 Ensure background scrolling when role selection popup appears.

### ISSUE THREAD

**Issue by AyushaNayabhari** [pyam-bee/OneByte-DineIn#5]
The user should be able to scroll down the dashboard while the pop-up appears for selecting their role.

**Comment by Subrina-bhandari** [comment]
The issue with the scrolling part while selecting the user in pop-up part has been updated. Below is the screenshot of the code which I used to make some changes to be able for scrolling the background. 
![image](https://github.com/pyam-bee/OneByte-DineIn/assets/119728073/db134471-3116-46f6-a47b-0842b1031b12)

![image](https://github.com/pyam-bee/OneByte-DineIn/assets/119728073/407e1ad9-a95b-4600-9341-0466eba9ebcb)
